### ISSUE TITLE
Add theme awareness

### ISSUE THREAD

**Issue by andyrichardson** [FormidableLabs/urql-devtools#171]
## About

~The theme being used by the user (light or dark) can be sourced using `chrome.devtools.panels.themeName`.~

> Lets avoid this method as it doesn't apply to the electron instance

--- 

Quick update on this, I've played around with different ideas but the simplest option so far seems to be a combination of filters:

```css
body {
  filter: invert(1) hue-rotate(180deg) saturate(3) brightness(1.085) contrast(0.99);
}
```

![Screenshot 2020-05-14 at 11 31 49](https://user-images.githubusercontent.com/10779424/81924087-87140e80-95d6-11ea-93b8-4f90f90d466e.png)

---

## Todo

 - [ ] Add a toggle to devtools to switch between dark and light mode
 - [ ] Persist theme state between reloads (if no persisted state, default to dark)
